const entries=[
    { id: 1, column1: '2000', column2: 'Shiv Sunder Das', column3: 'Bangladesh',searchColumn:'das' },
    { id: 2, column1: '2000', column2: 'Saba Karim', column3: 'Bangladesh',searchColumn:'karim' },
    { id: 3, column1: '2000', column2: 'Zaheer Khan', column3: 'Bangladesh',searchColumn:'khan' },
    { id: 4, column1: '2001', column2: 'Hemang Badani', column3: 'Zimbabwe',searchColumn:'badani' },
    { id: 5, column1: '2001', column2: 'Deep Dasgupta', column3: 'South Africa',searchColumn:'dasgupta' },
    { id: 6, column1: '2001', column2: 'Virender Sehwag', column3: 'South Africa',searchColumn:'sehwag' },
    { id: 7, column1: '2002', column2: 'Ajay Ratra', column3: 'Trinidad and Tobago',searchColumn:'ratra' },
    { id: 8, column1: '2002', column2: 'Parthiv Patel', column3: 'England',searchColumn:'patel' },
    { id: 9, column1: '2003', column2: 'Irfan Pathan', column3: 'Australia',searchColumn:'pathan' },
    { id: 10, column1: '2006', column2: 'RP Singh', column3: 'Pakistan',searchColumn:'singh' },
    { id: 11, column1: '2006', column2: 'Vikram Singh', column3: 'Antigua and Barbuda',searchColumn:'vikram' },
    { id: 12, column1: '2007', column2: 'Ramesh Powar', column3: 'Bangladesh',searchColumn:'powar' },
    { id: 13, column1: '2007', column2: 'Ishant Sharma', column3: 'Bangladesh',searchColumn:'sharma' },
    { id: 14, column1: '2010', column2: 'Abhimanyu Mithun', column3: 'Sri Lanka',searchColumn:'mithun' },
    { id: 15, column1: '2010', column2: 'Suresh Raina', column3: 'Sri Lanka',searchColumn:'raina' },
    { id: 16, column1: '2010', column2: 'Jaydev Unadkat', column3: 'South Africa',searchColumn:'unadkat' },
    { id: 17, column1: '2011', column2: 'Virat Kohli', column3: 'Jamaica',searchColumn:'kohli' },
    { id: 18, column1: '2011', column2: 'Praveen Kumar', column3: 'Jamaica',searchColumn:'kumar' },
    { id: 19, column1: '2011', column2: 'Abhinav Mukund', column3: 'Jamaica',searchColumn:'mukund' },
    { id: 20, column1: '2012', column2: 'Vinay Kumar', column3: 'Australia',searchColumn:'vinay' },
    { id: 21, column1: '2014', column2: 'Stuart Binny', column3: 'England',searchColumn:'binny' },
    { id: 22, column1: '2014', column2: 'Pankaj Singh', column3: 'England',searchColumn:'pankaj' },
    { id: 23, column1: '2014', column2: 'Karn Sharma', column3: 'Australia',searchColumn:'karn' },
    { id: 24, column1: '2014', column2: 'KL Rahul', column3: 'Australia',searchColumn:'rahul' },
    { id: 25, column1: '2015', column2: 'Naman Ojha', column3: 'Sri Lanka',searchColumn:'ojha' },
    { id: 26, column1: '2017', column2: 'Hardik Pandya', column3: 'Sri Lanka',searchColumn:'pandya' },
    { id: 27, column1: '2018', column2: 'Jasprit Bumrah', column3: 'South Africa',searchColumn:'bumrah' },
    { id: 28, column1: '2018', column2: 'Rishabh Pant', column3: 'England',searchColumn:'pant' },
    { id: 59, column1: '2018', column2: 'Hanuma Vihari', column3: 'England',searchColumn:'vihari' },
    { id: 30, column1: '2018', column2: 'Mayank Agarwal', column3: 'Australia',searchColumn:'agarwal' },
    { id: 31, column1: '2020', column2: 'Mohammed Siraj', column3: 'Australia',searchColumn:'siraj' },
    { id: 32, column1: '2020', column2: 'Shubman Gill', column3: 'Australia',searchColumn:'gill' },
    { id: 33, column1: '2021', column2: 'Navdeep Saini', column3: 'Australia',searchColumn:'saini' },
    { id: 34, column1: '2021', column2: 'T Natarajan', column3: 'Australia',searchColumn:'natarajan' },
    { id: 35, column1: '2021', column2: 'Washington Sundar', column3: 'Australia',searchColumn:'sundar' },

]

export default entries;